module.exports = {
    entry: './src/index.html',
    distDir: './dist',
    publicUrl: '/',
    cache: true,
    cacheDir: '.cache',
    minify: false,
    sourceMaps: true,
    hmr: true,
    target: 'browser',
    logLevel: 3,
    detailedReport: true,
    outDir: './dist',
    contentHash: false,
    global: false,
    scopeHoist: false,
    autoInstall: true,
    watch: true,
    https: false,
    port: 1234,
    open: true,
    rootDir: './',
    config: {
        browserslist: ['> 0.25%', 'not dead'],
    },
};
